# Generated by Django 2.0.1 on 2018-02-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_goods', '0003_auto_20180202_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
