# Generated by Django 2.0.1 on 2018-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_goods', '0004_typeinfo_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
