# Generated by Django 2.0.1 on 2018-01-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_user', '0002_auto_20180120_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usex',
            field=models.CharField(default='', max_length=1),
        ),
    ]
