# Generated by Django 2.0.1 on 2018-02-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ta_user', '0004_address'),
        ('ta_goods', '0007_auto_20180204_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=None, to='ta_goods.GoodInfo')),
                ('user', models.ForeignKey(on_delete=None, to='ta_user.User')),
            ],
        ),
    ]
